config/routes.rb
Rails.application.routes.draw do
  devise_for :gt_users
  root                  'gt_users#show'
  resources :return_users
  resources :gt_users, only: [:show]
  resources :items

end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :items
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
end

app/models/gt_user.rb
class GtUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 122 }
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :building
  belongs_to :item_type
  belongs_to :return_user
  before_save { self.title = title.downcase }
  validates :item_type_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates_inclusion_of :has_id, in: [true, false]
  validates :where_found, presence: true
  validates :building_id, presence: true
  validates :description, presence: true, length: { maximum: 65536 }
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
  has_many :items
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
end

app/models/return_user.rb
class ReturnUser < ActiveRecord::Base
  has_many :items
  validates :name, presence: true,  length: { maximum: 255 }
  validates :gtid, uniqueness: true, if: :gtid?
  validates :state_id, presence: true, uniqueness: true, unless: :gtid?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/gt_users_controller.rb
class GtUsersController < ApplicationController

  def show
    if gt_user_signed_in?
      @gt_user = GtUser.find_by params[:id]
    else
      redirect_to new_gt_user_session_path
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if gt_user_signed_in?
      @current_user = current_gt_user
      if @current_user = current_gt_user
        @grid = initialize_grid(Item,
          include: [:building, :item_type, :return_user],
          order: 'items.when_found',
          order_direction: 'desc'
          )
      else
        redirect_to new_gt_user_session_path
      end
    end
  end

  def new
    @item = Item.new
    if gt_user_signed_in?
      render :new
    else
      redirect_to new_gt_user_session_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "Item succesfully added"
      redirect_to items_path
    else
      render 'new'
    end
  end

  def update
    @item = Item.find params[:id]
    if @item.update(item_params)
      flash[:success] = "Item returned!"
      redirect_to items_path
    else
      redirect_to new_return_user_path
    end
  end

  def edit
    @item = Item.find params[:id]
  end

  private

  def item_params
    allow = [:building_id, :where_found, :when_found, :item_type_id, :title, :description, :has_id, :return_user_id]
    params.require(:item).permit(allow)
  end

  def update_item_params
    allow = [:building_id, :where_found, :when_found, :item_type_id, :title, :description]
    params.require(:item).permit(allow)
  end
end

app/controllers/return_users_controller.rb
class ReturnUsersController < ApplicationController

  def new
    @return_user = ReturnUser.new
    session[:return_user_item_id] ||= params[:item_id]
    @item = Item.find(session[:return_user_item_id])
    if gt_user_signed_in?
      render :new
    else
      redirect_to new_gt_user_session_path
    end
  end

  def create
    @return_user = ReturnUser.new(return_user_params)
    if @return_user.save
      @item = Item.find(session[:return_user_item_id])
      @item.return_user_id = @return_user.id
      if @item.save
        flash[:success] = "Person created and item returned!"
        session[:return_user_item_id] = nil
        redirect_to items_path
      else
        redirect_to new_return_user_path
      end
    else
      redirect_to new_return_user_path
    end
  end

  def show
    @return_user = ReturnUser.find(params[:id])
  end

  private
  def return_user_params
    allow = [:name, :gtid, :state_id]
    params.require(:return_user).permit(allow)
  end

  def item_params
    allow = [:return_user_id]
    params.require(:item).permit(allow)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/return_users_helper.rb
module ReturnUsersHelper
end

app/views/gt_users/show.html.erb
<h1><% @gt_user.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div>
        <%= link_to "Add Lost Item", new_item_path, class: 'btn btn-default form-control', id: 'user-show-button' %>
      </div>
      <div>
        <%= link_to "Find Lost Item", items_path, class: 'btn btn-default form-control', id: 'user-show-button' %>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<% provide(:title, 'Edit Lost Item') %>
<% @buildings = Building.all %>
<% @item_types = ItemType.all %>
<h1>Edit Item</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(@item) do |f| %>
        <%= render 'shared/add_item_error_messages' %>
        <%= f.input :building_id, collection: @buildings, input_html: { class: 'dropdown-toggle' } %>
        <%= f.input :where_found, input_html: { class: 'form-control' } %>
        <%= f.input :when_found, as: :datetime_picker %>
        <%= f.input :item_type_id, collection: @item_types, input_html: { class: 'dropdown-toggle' } %>
        <%= f.input :title, input_html: { class: 'form-control' } %>
        <%= f.input :description, input_html: { class: 'form-control' } %>
        <%= f.button :submit, input_html: { class: "btn btn-primary" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container-fluid table-responsive">
  <%= grid(@grid) do |g|
    g.column name: 'Item Type', attribute: 'name', assoc: :item_type do |item|
      item.item_type.name
    end
    g.column name: 'Title', attribute: 'title'
    g.column name: 'When Found' do |item|
      item.when_found.to_s(:long)
    end
    g.column name: 'Where Held', attribute: 'name', assoc: :building do |item|
      item.building.name
    end
    g.column name: 'Where Found', attribute: 'where_found'
    g.column name: 'Description', attribute: 'description'
    g.column name: 'Returned to', attribute: 'name', assoc: :return_user do |item|
      if item.return_user
        link_to(item.return_user.name, item.return_user)
      else
        link_to("Return item", url_for(controller: 'return_users', action: 'new', item_id: item.id))
      end
    end
    g.column name: 'Edit Item' do |item|
      link_to("Edit", edit_item_path(item.id))
    end
  end %>
</div>

app/views/items/new.html.erb
<% provide(:title, 'Add Lost Item') %>
<% @buildings = Building.all %>
<% @item_types = ItemType.all %>
<h1>Add Lost Items</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(@item) do |f| %>
        <%= render 'shared/add_item_error_messages' %>
        <%= f.input :building_id, collection: @buildings, input_html: { class: 'dropdown-toggle' } %>
        <%= f.input :where_found, input_html: { class: 'form-control' } %>
        <%= f.input :when_found, as: :datetime_picker %>
        <%= f.input :item_type_id, collection: @item_types, input_html: { class: 'dropdown-toggle' } %>
        <%= f.input :title, input_html: { class: 'form-control' } %>
        <%= f.input :description, input_html: { class: 'form-control' } %>
        <% f.input :has_id, label: "Has ID?", as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.button :submit, input_html: { class: "btn btn-primary" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/return_item.html.erb
<% provide(:title, 'Return Lost Item') %>
<% @return_users = ReturnUser.all %>

<h1>Return Lost Item</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(@item) do |f| %>
        <%= f.input :return_user_id, collection: @return_users, input_html: { class: 'dropdown-toggle' } %>
        <%= f.button :submit, input_html: { class: "btn btn-primary" } %>
      <% end %>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(@return_user) do |f| %>
        <%= f.input :name, input_html: { class: 'form-control' } %>
        <%= f.input :gtid, input_html: { class: 'form-control'} %>
        <%= f.input :state_id, input_html: { class: 'form-control' } %>
        <%= f.button :submit, input_html: { class: "btn btn-primary" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sample Oreatan", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if gt_user_signed_in? %>
          <li><%= link_to("Log out", destroy_gt_user_session_url, method: 'delete')%></li>
        <% else %>
          <li><% link_to "Log in", new_gt_user_session_path %></li>
          <li><%= link_to "Sign up", new_gt_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oreatan</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/return_users/new.html.erb
<% provide(:title, 'Return Lost Item') %>
<% @return_users = ReturnUser.all %>

<h1>Return Lost Item</h1>

<div class="container">

</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to("Choose Existing User", '#', class: "btn btn-default", id: "select_existing_user") %>
      <%= simple_form_for(@item) do |f| %>
        <%= f.input :return_user_id, collection: @return_users, input_html: { class: 'dropdown-toggle' } %>
        <%= f.button :submit, input_html: { class: "btn btn-primary" } %>
      <% end %>
    </div>
  </div>
</div>

<br>
<div class="container">

</div>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to("Create a new user", '#', class: "btn btn-default", id: "create_new_user") %>
      <%= simple_form_for(@return_user) do |f| %>
        <%= f.input :name, input_html: { class: 'form-control' } %>
        <%= f.input :gtid, input_html: { class: 'form-control'} %>
        <%= f.input :state_id, input_html: { class: 'form-control' } %>
        <%= f.button :submit, input_html: { class: "btn btn-primary" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/return_users/show.html.erb
<h1><%= @return_user.name %></h1>

<div class="container">
  <p>
    <% if @return_user.gtid? %>
      GTID: <%= @return_user.gtid %>
    <% else %>
      State ID: <%= @return_user.state_id %>
    <% end %>
  </p>
</div>

app/views/shared/_add_item_error_messages.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_signup_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>